version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: identity-server
    restart: unless-stopped
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: jdbc:postgresql://${KC_DB_HOST}:${KC_DB_PORT}/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY: ${KC_PROXY}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_PROXY_HEADERS: "xforwarded"
      # JVM memory options: sets initial heap size to 256MB and max heap size to 512MB
      JAVA_OPTS_APPEND: "-Xms256m -Xmx512m"
    ports:
      - "8080:8080"
    volumes:
      # /opt/keycloak-certs/tls.crt on the host is mapped to /etc/x509/https/tls.crt in the container (read-only)
      - /opt/keycloak-certs/tls.crt:/etc/x509/https/tls.crt:ro
      - /opt/keycloak-certs/tls.key:/etc/x509/https/tls.key:ro
      - ./providers/thakacreations.keycloak-2fa-sms-authenticator.jar:/opt/keycloak/providers/thakacreations.keycloak-2fa-sms-authenticator.jar
      - ./providers/keycloak-usermanagement-provider-1.0.0-all.jar:/opt/keycloak/providers/keycloak-usermanagement-provider-1.0.0-all.jar
      - keycloak_data:/opt/keycloak/data
    command:
      - start
      - --https-certificate-file=/etc/x509/https/tls.crt
      - --https-certificate-key-file=/etc/x509/https/tls.key

volumes:
  keycloak_data:
